----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date:    21:29:29 10/05/2025 
-- Design Name: 
-- Module Name:    MicroBasic - Behavioral 
-- Project Name: 
-- Target Devices: 
-- Tool versions: 
-- Description: 
--
-- Dependencies: 
--
-- Revision: 
-- Revision 0.01 - File Created
-- Additional Comments: 
--
----------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

-- Uncomment the following library declaration if using
-- arithmetic functions with Signed or Unsigned values
--use IEEE.NUMERIC_STD.ALL;

-- Uncomment the following library declaration if instantiating
-- any Xilinx primitives in this code.
--library UNISIM;
--use UNISIM.VComponents.all;

use work.microbasic_code.all;	-- generated by MCC 
use work.microbasic_map.all;	-- generated by MCC

entity MicroBasic is
    Port ( reset : in  STD_LOGIC;
           clk : in  STD_LOGIC;
			  nBUSREQ : out STD_LOGIC;
           nBUSACK : in  STD_LOGIC;
			  nRD : out STD_LOGIC;
			  nWR : out STD_LOGIC;
			  ABUS: out STD_LOGIC_VECTOR(15 downto 0);
			  DBUS: inout STD_LOGIC_VECTOR(7 downto 0);
			  -- output char
			  outchar: out STD_LOGIC_VECTOR(7 downto 0);
			  outchar_send: buffer STD_LOGIC;
			  outchar_ready: in STD_LOGIC;
			  -- input char
			  inchar: in STD_LOGIC_VECTOR(7 downto 0);
			  inchar_ready: in STD_LOGIC;
			  -- debug / trace UART output
           baudrate : in  STD_LOGIC;
           debug_txd : out  STD_LOGIC;
           debug_bus : out  STD_LOGIC_VECTOR(15 downto 0));
end MicroBasic;

architecture Behavioral of MicroBasic is

-- control unit
signal ui_address: std_logic_vector(CODE_ADDRESS_WIDTH - 1 downto 0);
signal ui_nextinstr: std_logic_vector(CODE_ADDRESS_WIDTH -1  downto 0);

-- Intermediate languge
signal IL_PC: std_logic_vector(10 downto 0); -- 9 bits enough, but keep it compatible with other implementations
signal IL_OP: std_logic_vector(7 downto 0);
signal IL_PC_VALID: std_logic;
signal il_codeByte: std_logic_vector(7 downto 0);

-- single char output
signal CHAROUT: std_logic_vector(7 downto 0);
signal CHAROUT_SEND, CHAROUT_READY: std_logic;

-- single char input
signal CHARIN: std_logic_vector(7 downto 0);
signal charin_equ_db, charin_printable, charin_ready: std_logic; 

-- serial debug port
signal DBGINDEX: std_logic_vector(5 downto 0); -- 64 entries supported
signal DBG_READY, dbg_start: std_logic;

-- external memory related
signal MAR: std_logic_vector(15 downto 0);
signal MDR: std_logic_vector(7 downto 0);
signal mdr_is_zero: std_logic;

-- other
signal T: std_logic_vector(15 downto 0);
signal InlEnd: std_logic_vector(15 downto 0);
signal inlend_max, inlend_min: std_logic;

begin

nBUSREQ <= mb_nBUSREQ;
-- Tristate system bus
nRD <= mb_nRD when (nBUSACK = '0') else 'Z';
nWR <= mb_nWR when (nBUSACK = '0') else 'Z';

ABUS <= MAR when (nBUSACK = '0') else "ZZZZZZZZZZZZZZZZ";
update_MAR: process(clk, mb_MAR)
begin
	if (rising_edge(clk)) then
		case mb_MAR is
	--			when MAR_same =>
	--				MAR <= MAR;
			when MAR_InlEnd =>
				MAR <= InlEnd;
			when others =>
				null;
		end case;
	end if;
end process;

DBUS <= MDR when ((mb_nWR or nBUSACK) = '0') else "ZZZZZZZZ";
update_MDR: process(clk, mb_MDR)
begin
	if (rising_edge(clk)) then
		case mb_MDR is
	--			when MDR_same =>
	--				MDR <= MDR;
			when MDR_from_Bus =>
				MDR <= DBUS;
			when MDR_zero =>
				MDR <= (others => '0');
			when MDR_CHARIN =>
				MDR <= CHARIN;
			when others =>
				null;
		end case;
	end if;
end process;

mdr_is_zero <= '1' when (MDR = X"00") else '0';

-- ROM containing the IL language instructions
cu_il: entity work.il_rom Port map ( 
		a => IL_PC,
      d => il_codeByte,
		a_is_valid => IL_PC_VALID
		);

-- mapping IL opcode to microcode routine start
mb_instructionstart <= mb_mapper(to_integer(unsigned(il_op)));

-- control unit
cu_mb: entity work.microbasic_control_unit
     Generic map (
			CODE_DEPTH => CODE_ADDRESS_WIDTH,
			IF_WIDTH => CODE_IF_WIDTH
     )
     Port map ( 
			-- standard inputs
			reset => reset,
			clk => clk,
			-- design specific inputs
			seq_cond => mb_seq_cond,
			seq_then => mb_seq_then,
			seq_else => mb_seq_else,
			seq_fork => mb_instructionstart(8 downto 0),	-- IL opcode mapper input
			-- condition bits
			cond(seq_cond_true) => '1',
			cond(seq_cond_CHAROUT_BIT7) => CHAROUT(7),
			cond(seq_cond_CHAROUT_READY) => CHAROUT_READY,
			cond(seq_cond_IL_PC_VALID) => IL_PC_VALID,
			cond(seq_cond_DBG_READY) => DBG_READY,
			cond(seq_cond_MDR_IS_ZERO) => mdr_is_zero,
			cond(seq_cond_nBUSACK) => nBUSACK,
			cond(seq_cond_INLEND_MAX) => inlend_max,
			cond(seq_cond_INLEND_MIN) => inlend_min,
			cond(seq_cond_CHARIN_PRINTABLE) => charin_printable,
			cond(seq_cond_CHARIN_EQU_DB) => charin_equ_db,
			cond(seq_cond_CHARIN_READY) => charin_ready,
			cond(seq_cond_dummy_C) => '1',
			cond(seq_cond_dummy_D) => '1',
			cond(seq_cond_dummy_E) => '1',
			cond(seq_cond_false) => '0',
			-- outputs
			ui_nextinstr => ui_nextinstr,
			ui_address => ui_address
		);

charin_equ_db <= '1' when (CHARIN = mb_directByte) else '0';
charin_printable <= '0' when (CHARIN(7 downto 5) = "000") else (not CHARIN(7)); -- TODO: Add 0x7F 
inlend_max <= '1' when (InlEnd = X"00FF") else '0';
inlend_min <= '1' when (InlEnd = X"0000") else '0';

-- show IL code an microinstruction address on debug port
--	debug_bus <= il_op & ui_address(7 downto 0); 
--	debug_bus <= "00" & DBGINDEX & ui_address(7 downto 0); 
	debug_bus <= CHAROUT & CHARIN;
	
-- get the microcode instruction 
mb_uinstruction <= mb_microcode(to_integer(unsigned(ui_address)));
		
update_IL_PC: process(clk, mb_IL_PC)
 begin
	if (rising_edge(clk)) then
		case mb_IL_PC is
--			when IL_PC_same =>
--				IL_PC <= IL_PC;
			when IL_PC_zero =>
				IL_PC <= (others => '0');
			when IL_PC_inc =>
				IL_PC <= std_logic_vector(unsigned(IL_PC) + 1);
			when IL_PC_T =>
				IL_PC <= T(10 downto 0);
			when IL_PC_pc_plus_off6 =>
				-- a bit bizarre offset
				if (IL_OP(5) = '1') then
					IL_PC <= std_logic_vector(unsigned(IL_PC) + unsigned(IL_OP(4 downto 0)));
				else
					IL_PC <= std_logic_vector(unsigned(IL_PC) - unsigned(IL_OP(4 downto 0)));
				end if;
			when others =>
				null;
		end case;
 end if;
end process;
		
 update_IL_OP: process(clk, mb_IL_OP)
 begin
	if (rising_edge(clk)) then
	    if (mb_IL_OP = IL_OP_from_interpreter) then
		    IL_OP <= il_codeByte;
	    end if;
 end if;
 end process;
		
update_T: process(clk, mb_T)
begin
	if (rising_edge(clk)) then
		case mb_T is
--			when T_same =>
--				T <= T;
			when T_IL_PC =>
				T <= "00000" & IL_PC;
			when others =>
				null;
		end case;
 end if;
end process;
	
-- input buffer pointer
 update_InlEnd: process(clk, mb_InlEnd)
 begin
	if (rising_edge(clk)) then
		case mb_InlEnd is
--			when InLend_same =>
--				InLend <= InLend;
			when InlEnd_InLine =>
				--InLend <= InLine;
				InlEnd <= (others => '0');	-- TODO!
			when InlEnd_inc =>
				InlEnd <= std_logic_vector(unsigned(InlEnd) + 1);
			when InLend_dec =>
				InlEnd <= std_logic_vector(unsigned(InlEnd) - 1);
			when others =>
				null;
		end case;
 end if;
 end process;
	
-- output port (1 ASCII char at a time, usually goes to UART)
 update_CHAROUT: process(clk, mb_CHAROUT)
 begin
	if (rising_edge(clk)) then
		case mb_CHAROUT is
			when CHAROUT_same =>
				CHAROUT_SEND <= '0';					-- pulse low
				CHAROUT <= CHAROUT;
			when CHAROUT_from_interpreter =>
				CHAROUT_SEND <= '1';					-- pulse high when data loaded
				CHAROUT <= il_codeByte;
			when CHAROUT_from_microcode =>
				CHAROUT_SEND <= '1';					-- pulse high when data loaded
				CHAROUT <= mb_directByte;
			when CHAROUT_from_charin =>
				CHAROUT_SEND <= '1';					-- pulse high when data loaded
				CHAROUT <= CHARIN;
			when others =>
				null;
		end case;
 end if;
 end process;
 
-- see http://www.ittybittycomputers.com/IttyBitty/TinyBasic/TinyBasic.c line 776
outchar <= CHAROUT and X"7F";
outchar_send <= CHAROUT_SEND;
CHAROUT_READY <= outchar_ready; 
 
-- input character
on_inchar_ready: process(reset, inchar_ready, mb_gotChar)
begin
	if ((reset or mb_gotChar) = '1') then
		CHARIN <= (others => '0');
		charin_ready <= '0';
	else
		if (rising_edge(inchar_ready)) then
			CHARIN <= inchar;
			charin_ready <= '1';
		end if;
	end if;
end process;
	
-- serial debug port implementation
tracer: entity work.serialtracer2 Port map (
		reset => reset,
		clk => baudrate,
		enable => '1',
		start => dbg_start,
		index => DBGINDEX,
		data(3) => '0',
		data(2 downto 0) => IL_PC(10 downto 8),
		data(7 downto 4) => IL_PC(7 downto 4),
		data(11 downto 8) => IL_PC(3 downto 0),
		data(15 downto 12) => il_codeByte(7 downto 4),
		data(19 downto 16) => il_codeByte(3 downto 0),
		data(23 downto 20) => MDR(7 downto 4),
		data(27 downto 24) => MDR(3 downto 0),
		data(31 downto 28) => X"F",
		txd => debug_txd,
		ready => DBG_READY
		);
	
 update_DBGINDEX: process(clk, mb_DBGINDEX)
 begin
	if (rising_edge(clk)) then
		case mb_DBGINDEX is
--			when DBGINDEX_same =>
--				DBGINDEX <= DBGINDEX;
			when DBGINDEX_from_microcode =>
				DBGINDEX <= mb_directByte(5 downto 0);
				dbg_start <= '1';
			when DBGINDEX_zero =>
				DBGINDEX <= (others => '0');
				dbg_start <= '0';
			when DBGINDEX_crlf =>
				DBGINDEX <= (others => '1'); -- points to last index in the table
				dbg_start <= '1';
			when others =>
				null;
		end case;
 end if;
 end process;

end Behavioral;

