----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date:    21:29:29 10/05/2025 
-- Design Name: 
-- Module Name:    MicroBasic - Behavioral 
-- Project Name: 
-- Target Devices: 
-- Tool versions: 
-- Description: 
--
-- Dependencies: 
--
-- Revision: 
-- Revision 0.01 - File Created
-- Additional Comments: 
--
----------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

-- Uncomment the following library declaration if using
-- arithmetic functions with Signed or Unsigned values
--use IEEE.NUMERIC_STD.ALL;

-- Uncomment the following library declaration if instantiating
-- any Xilinx primitives in this code.
--library UNISIM;
--use UNISIM.VComponents.all;

use work.microbasic_code.all;	-- generated by MCC 
use work.microbasic_map.all;	-- generated by MCC

entity MicroBasic is
    Port ( reset : in  STD_LOGIC;
           clk : in  STD_LOGIC;
           nWAIT : in  STD_LOGIC;
           nBUSACK : in  STD_LOGIC;
           baudrate : in  STD_LOGIC;
           debug_txd : out  STD_LOGIC;
           debug_bus : out  STD_LOGIC_VECTOR(15 downto 0));
end MicroBasic;

architecture Behavioral of MicroBasic is

-- control unit
signal ui_address: std_logic_vector(CODE_ADDRESS_WIDTH - 1 downto 0);
signal ui_nextinstr: std_logic_vector(CODE_ADDRESS_WIDTH -1  downto 0);

-- Intermediate languge
signal IL_PC: std_logic_vector(10 downto 0); -- 9 bits enough, but keep it compatible with other implementations
signal il_op: std_logic_vector(7 downto 0);
signal IL_PC_VALID: std_logic;

-- serial debug port
signal DBGCHAR: std_logic_vector(7 downto 0);
signal DBG_READY, dbg_start: std_logic;

-- other
signal T: std_logic_vector(15 downto 0);

begin

-- ROM containing the IL language instructions
cu_il: entity work.il_rom Port map ( 
		a => il_pc,
      d => il_op,
		a_is_valid => IL_PC_VALID
		);

-- mapping IL opcode to microcode routine start
mb_instructionstart <= mb_mapper(to_integer(unsigned(il_op)));

-- control unit
cu_mb: entity work.microbasic_control_unit
     Generic map (
			CODE_DEPTH => CODE_ADDRESS_WIDTH,
			IF_WIDTH => CODE_IF_WIDTH
     )
     Port map ( 
			-- standard inputs
			reset => reset,
			clk => clk,
			-- design specific inputs
			seq_cond => mb_seq_cond,
			seq_then => mb_seq_then,
			seq_else => mb_seq_else,
			seq_fork => mb_instructionstart(8 downto 0),	-- IL opcode mapper input
			-- condition bits
			cond(seq_cond_true) => '1',
			cond(seq_cond_nWAIT) => nWAIT,
			cond(seq_cond_nBUSACK) => nBUSACK,
			cond(seq_cond_IL_PC_VALID) => IL_PC_VALID,
			cond(seq_cond_DBG_READY) => DBG_READY,
			cond(seq_cond_dummy_5) => '1',
			cond(seq_cond_dummy_6) => '1',
			cond(seq_cond_dummy_7) => '1',
			cond(seq_cond_dummy_8) => '1',
			cond(seq_cond_dummy_9) => '1',
			cond(seq_cond_dummy_A) => '1',
			cond(seq_cond_dummy_B) => '1',
			cond(seq_cond_dummy_C) => '1',
			cond(seq_cond_dummy_D) => '1',
			cond(seq_cond_dummy_E) => '1',
			cond(seq_cond_false) => '0',
			-- outputs
			ui_nextinstr => ui_nextinstr,
			ui_address => ui_address
		);

-- show IL code an microinstruction address on debug port
--	debug_bus <= il_op & ui_address(7 downto 0); 
	debug_bus <= DBGCHAR & ui_address(7 downto 0); 
	
-- get the microcode instruction 
mb_uinstruction <= mb_microcode(to_integer(unsigned(ui_address)));
		
update_IL_PC: process(clk, mb_IL_PC)
 begin
	if (rising_edge(clk)) then
		case mb_IL_PC is
--			when IL_PC_same =>
--				IL_PC <= IL_PC;
			when IL_PC_zero =>
				IL_PC <= (others => '0');
			when IL_PC_inc =>
				IL_PC <= std_logic_vector(unsigned(IL_PC) + 1);
			when IL_PC_T =>
				IL_PC <= T(10 downto 0);
			when others =>
				null;
		end case;
 end if;
end process;
		
update_T: process(clk, mb_T)
begin
	if (rising_edge(clk)) then
		case mb_T is
--			when T_same =>
--				T <= T;
			when T_IL_PC =>
				T <= "00000" & IL_PC;
			when others =>
				null;
		end case;
 end if;
end process;
	
tracer: entity work.serialtracer Port map (
		reset => reset,
		clk => baudrate,
		start => dbg_start,
		char => DBGCHAR,
		data(3) => '0',
		data(2 downto 0) => IL_PC(10 downto 8),
		data(7 downto 4) => IL_PC(7 downto 4),
		data(11 downto 8) => IL_PC(3 downto 0),
		data(15 downto 12) => il_op(7 downto 4),
		data(19 downto 16) => il_op(3 downto 0),
		data(23 downto 20) => X"F",
		data(27 downto 24) => X"F",
		data(31 downto 28) => X"F",
		txd => debug_txd,
		ready => DBG_READY
		);
	
-- serial debug port implementation
update_DBGCHAR: process(clk, mb_DBGCHAR)
begin
if (rising_edge(clk)) then
	case mb_DBGCHAR is
--			when DBGCHAR_same =>
--				DBGCHAR <= DBGCHAR;
		when DBGCHAR_directByte =>
			DBGCHAR <= mb_directByte;
			dbg_start <= '1';
		when DBGCHAR_zero =>
			DBGCHAR <= (others => '0');
			dbg_start <= '0';
		when others =>
			null;
	end case;
end if;
end process;
		
end Behavioral;

