----------------------------------------------------------------------------------
-- Company: 		 https://hackaday.io/projects/hacker/233652
-- Engineer: 		 zpekic@hotmail.com
-- 
-- Create Date:    21:29:29 10/05/2025 
-- Design Name: 
-- Module Name:    MicroBasic - Behavioral 
-- Project Name: 
-- Target Devices: 
-- Tool versions:  ISE 14.7, mcc - microcode compiler
-- Description: https://hackaday.io/project/204482-celebrating-50-years-of-tiny-basic
--
-- Dependencies: 
--
-- Revision: 
-- Revision 0.01 - File Created
-- Additional Comments: 
--
----------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

-- Uncomment the following library declaration if using
-- arithmetic functions with Signed or Unsigned values
use IEEE.NUMERIC_STD.ALL;

-- Uncomment the following library declaration if instantiating
-- any Xilinx primitives in this code.
--library UNISIM;
--use UNISIM.VComponents.all;

use work.microbasic_package.all;
use work.microbasic_code.all;	-- generated by MCC 
use work.microbasic_map.all;	-- generated by MCC

entity MicroBasic is
		Generic (
			MSB: positive;
			-- TODO: find the actual end of RAM instead of hard coding it here 
			Core_End: std_logic_vector(15 downto 0)
			);
		Port ( 
			reset : in  STD_LOGIC;
			clk : in  STD_LOGIC;
			clk_tick: in STD_LOGIC;
			-- GOTO cache state
			cache_empty : out STD_LOGIC;
			cache_full : out STD_LOGIC;
			-- Intermediate language (IL) read-only memory
			IL_A: out STD_LOGIC_VECTOR(10 downto 0);
			IL_D: in STD_LOGIC_VECTOR(7 downto 0);
			--TB_EXTENDED: in STD_LOGIC;
			-- Input line and Basic program memory (up to 64k)
			nBUSREQ : in STD_LOGIC;
			nBUSACK : buffer STD_LOGIC;
			nREADY: in STD_LOGIC;
			nRD : out STD_LOGIC;
			nWR : out STD_LOGIC;
			ABUS: out STD_LOGIC_VECTOR(15 downto 0);
			DBUS: inout STD_LOGIC_VECTOR(7 downto 0);
			NMI: in STD_LOGIC;
			INT: in STD_LOGIC;
			INTACK: buffer STD_LOGIC;
			-- output char
			outchar: out STD_LOGIC_VECTOR(7 downto 0);
			outchar_send: buffer STD_LOGIC;
			outchar_ready: in STD_LOGIC;
			-- input char
			inchar: in STD_LOGIC_VECTOR(7 downto 0);
			inchar_ready: in STD_LOGIC;
			-- debug / trace UART output
			overflowEnable: in STD_LOGIC;
			traceEnable: in STD_LOGIC;
			baudrate : in  STD_LOGIC;
			debug_txd : out  STD_LOGIC;
			debug_uipc: out STD_LOGIC_VECTOR(8 downto 0);
			debug_t: out STD_LOGIC_VECTOR(15 downto 0);
			debug_sel: in STD_LOGIC_VECTOR(1 downto 0);
			debug_bus : out STD_LOGIC_VECTOR(31 downto 0));
end MicroBasic;

architecture Behavioral of MicroBasic is

-- generics
constant MSB_DOUBLE: positive := (MSB + 1) * 2 - 1;							-- 31 / 63
constant MSB_HALF: positive := (MSB + 1) / 2 - 1;								-- 7 / 15
constant ZERO: std_logic_vector(MSB downto 0) := (others => '0');			-- X"0000" / X"00000000"
constant MINUS_ONE: std_logic_vector(MSB downto 0) := (others => '1');	-- X"FFFF" / X"FFFFFFFF"
constant BITCNT: std_logic_vector(4 downto 0) := std_logic_vector(to_unsigned(MSB, 5));		-- 15 / 31
alias IS_CPU32: std_logic is BITCNT(4);																		-- '0' / '1'
constant STEPCNT: std_logic_vector(7 downto 0) := std_logic_vector(to_unsigned(MSB + 1, 8)); -- X"10" / X"20"
constant BCDDIGITS: positive := (MSB + 9) / 4; 	-- 6 / 10
constant CP_OFF: positive := MSB_HALF + 1;		-- 8 / 16
type ram16xHalf is array (0 to 15) of std_logic_vector(MSB_HALF downto 0);
type ram32xFull is array (0 to 31) of std_logic_vector(MSB downto 0);
type ram8xFull is array(0 to 7) of std_logic_vector(MSB downto 0);
constant INT_VECTORS: ram8xFull := (
	-- Basic line numbers to GOSUB when interrupt levels 0 to 7 are serviced
	std_logic_vector(to_unsigned(0, MSB + 1)),		-- IL = 0, no interrupt
	std_logic_vector(to_unsigned(32100, MSB + 1)),	-- IL = 1, INT
	std_logic_vector(to_unsigned(32200, MSB + 1)),	-- IL = 2, not used
	std_logic_vector(to_unsigned(32300, MSB + 1)),	-- IL = 3, not used
	std_logic_vector(to_unsigned(32400, MSB + 1)),	-- IL = 4, not used
	std_logic_vector(to_unsigned(32500, MSB + 1)),	-- IL = 5, not used
	std_logic_vector(to_unsigned(32600, MSB + 1)),	-- IL = 6, not used 
	std_logic_vector(to_unsigned(32700, MSB + 1))	-- IL = 7, NMI
);


-- control unit
signal ui_address: std_logic_vector(CODE_ADDRESS_WIDTH - 1 downto 0);
signal ui_nextinstr: std_logic_vector(CODE_ADDRESS_WIDTH -1  downto 0);
-- must match the location of the label of same name in the microcode for BUSREQ/BUSACK to work 
constant CHKBUSREQ: std_logic_vector(CODE_ADDRESS_WIDTH - 1 downto 0) := "000001011";

-- Intermediate language
signal IL_PC, XQhere: std_logic_vector(10 downto 0);	-- 9 bits enough, but keep it compatible with other implementations
signal IL_OP: std_logic_vector(7 downto 0);				-- CPU instruction register			
alias IL_OFF5: std_logic_vector(4 downto 0) is IL_OP(4 downto 0);
alias il_codeByte: std_logic_vector(7 downto 0) is IL_D;
signal off_is_zero: std_logic;

-- some IL opcodes that are useful to be known to hardware, not just the microcode
constant OP_GS: std_logic_vector(7 downto 0) := X"14";	-- Go Subroutine (push to Basic return stack)
constant OP_RS: std_logic_vector(7 downto 0) := X"15";	-- ReStore (pop from Basic return stack)
constant OP_GO: std_logic_vector(7 downto 0) := X"16";	-- GO (to)
constant OP_DV: std_logic_vector(7 downto 0) := X"1B";	-- DiVide
constant OP_CP: std_logic_vector(7 downto 0) := X"1C";	-- ComPare
constant OP_NX: std_logic_vector(7 downto 0) := X"1D";	-- NeXt statement
constant OP_NC: std_logic_vector(7 downto 0) := X"1E";	-- Next statement after Colon
constant OP_PQ: std_logic_vector(7 downto 0) := X"21";	-- Print basic string (from RAM to output)
constant OP_GL: std_logic_vector(7 downto 0) := X"27";	-- Get Line
constant OP_RT: std_logic_vector(7 downto 0) := X"2F";	-- ReTurn (pop from IL return stack)
-- extended Tiny Basic specific opcode
constant OP_FS: std_logic_vector(7 downto 0) := X"25";	-- For Start
constant OP_SA: std_logic_vector(7 downto 0) := X"28";	-- Switch on Alpha character

-- single char output
signal CHAROUT: std_logic_vector(7 downto 0);
signal CHAROUT_SEND, CHAROUT_READY, caret_escape, is_pq: std_logic;
signal lz: std_logic := '1';
signal hex_ascii: std_logic_vector(7 downto 0);

-- single char input
signal CHARIN: std_logic_vector(7 downto 0);
signal charin_equ_db, charin_printable, charin_ready, charin_is_break: std_logic; 

-- serial debug port
signal DBGINDEX: std_logic_vector(5 downto 0); -- 64 entries supported
signal DBG_READY, dbg_start: std_logic;

-- external memory interface (stores Basic code and input buffer)
signal MAR: std_logic_vector(15 downto 0);
signal MDR, MDR_UpperCase: std_logic_vector(7 downto 0);
signal mdr_is_num, mdr_is_alpha, mdr_is_lowercase, mdr_is_uppercase: std_logic;
signal mdr_matches_db, mdr_matches_ilcodebyte, mdr_matches_varname, mdr_matches_ilcodebyte_alt_varname: std_logic;

-- key pointers (memory map constants, TODO: make them variable to configure RAM layout and size) 
constant Inline_Start: std_logic_vector(15 downto 0) := X"0000";	-- input buffer at start of RAM
constant Inline_End: std_logic_vector(15 downto 0) := X"007F";		-- input buffer up to 128 characters  	
constant Prog_Start: std_logic_vector(15 downto 0) := X"0080"; 	-- Basic program right after that

-- key pointers (for parsing)
signal BP, BP_saved: std_logic_vector(15 downto 0);
signal SvPt, BE: std_logic_vector(15 downto 0);
signal bp_in_inpline, svp_in_inpline: std_logic;
signal InlEnd, LS, LE, PrgEnd: std_logic_vector(15 downto 0);
signal inlend_max, inlend_min: std_logic;
signal inlend_max_alt_basline_found, inlend_min_alt_impline_empty, basline_found, impline_empty: std_logic;
signal nbusreq_alt_nready: std_logic;

-- expression stack, 32 half-words / 16 words
signal ExpStack: ram16xHalf;
signal ExpSP: std_logic_vector(4 downto 0);			-- stack pointer points to free byte
signal ExpSwapR, ExpSwapS: std_logic_vector(4 downto 0);	-- pointers used in SX IL instruction
signal estack_is_full, estack_is_empty: std_logic;
signal SwapR, SwapS: std_logic_vector(MSB_HALF downto 0);
signal ExpSTHi, ExpSTLo: std_logic_vector(MSB_HALF downto 0);

-- IL return stack (JS / RT)
signal RetStack: ram16x16;
signal RetSP: std_logic_vector(3 downto 0);			-- stack pointer points to free word
signal rstack_is_empty, rstack_is_full: std_logic;

-- Basic stack (GOSUB/RETURN)
signal BasStack: ram16x36;
signal BasSP: std_logic_vector(3 downto 0);			-- stack pointer points to free entry
signal bstack_is_empty, bstack_is_full: std_logic;

-- stack error conditions
signal stack_is_full, stack_is_empty: std_logic;

-- Basic variables A-Z are stored internally in 32*48 RAM, few locations unused
signal vars: ram32xFull;
signal vars_for, vars_next: ram32x16;
signal vars_index, var_name: std_logic_vector(7 downto 0); 	-- 8 bits to make some arithmetic easier
signal var_address: integer range 0 to 31;
signal BasicFor, BasicNext: std_logic_vector(15 downto 0);		
signal BasicVar: std_logic_vector(MSB downto 0);		
signal for_set, next_set: std_logic;
signal for_v: std_logic_vector(31 downto 0)  := (others => '0');
signal next_v: std_logic_vector(31 downto 0) := (others => '0');
signal lino_var: std_logic_vector(15 downto 0) := X"0000";

-- ALU with own internal state
signal bcd_sum: std_logic_vector((BCDDIGITS * 4 - 1) downto 0);	-- 24/40 bits to contain BCD digits e.g. 032767
signal Y, Y_saved: std_logic_vector(MSB_DOUBLE downto 0);			-- double size needed for MUL, DIV, BCD conversion
alias ListFrom: std_logic_vector(MSB downto 0) is Y(MSB_DOUBLE downto (MSB + 1));
alias ListTo: std_logic_vector(MSB downto 0) is Y(MSB downto 0);
alias YHi: std_logic_vector(MSB downto 0) is Y(MSB_DOUBLE downto (MSB + 1));
alias YLo: std_logic_vector(MSB downto 0) is Y(MSB downto 0);
signal R, S: std_logic_vector(MSB downto 0);			-- ALU input arguments are 16 bit
signal s_plus_r, s_minus_r, neg_r, neg_s, neg_ylo, neg_yhi: std_logic_vector(MSB downto 0);
signal t_plus_r, t_minus_s: std_logic_vector(MSB downto 0);
signal s_mul_r: std_logic_vector(MSB_DOUBLE downto 0);		-- output of combinatorial multiplier
signal subc: std_logic_vector((MSB + 1) downto 0);				-- 17 bits, MSB is carry out which is needed in division step 
signal y_zero, r_is_zero: std_logic;								-- combinatorial state of Y and R
signal r_is_zero_full, r_is_zero_16: std_logic;
signal y_zero_alt_cp_skip, cp_skip: std_logic;					-- compare flags
signal alu_sign, alu_overflow, alu_ready, alu_s15: std_logic;	-- state needed for BCD, signed division
alias ls_params_ok: std_logic is alu_ready;
alias ls_in_range: std_logic is alu_sign;
alias ls_passed_end: std_logic is alu_overflow;
signal plus_overflow, minus_overflow, neg_overflow, mul_overflow, mul_pos16, mul_neg16, s_equ_r, s_gt_r: std_logic;

-- Basic line number
signal Lino: std_logic_vector(15 downto 0) := X"0000";
signal Lino_bcd: std_logic_vector(19 downto 0) := X"00000"; -- converted to BCD for tracer only
signal is_runmode, is_runmode_perf: std_logic;		-- 0 for commands, 1 for RUN

-- GOTO cache lookup convenience
alias Lino_index: std_logic_vector(4 downto 0) is Lino(4 downto 0);
alias Lino_tag: std_logic_vector(10 downto 0) is Lino(15 downto 5);

-- built in performance counters while Basic program is running
signal cnt_perf, cnt_perf1000: std_logic_vector(15 downto 0);
signal clk_perf, pulse_fetch, executing_nx, executing_nc: std_logic;

-- interrupts 
signal intreq, y_sign_alt_intreq: std_logic;
signal il_new, il_previous, il_current: std_logic_vector(3 downto 0);
signal lino_int: std_logic_vector(MSB downto 0); -- 32 or 16 bit to make it compatible with ExpStack width

-- GOTO cache - 2-way, 32 entries
signal cache_0, cache_1: ram32x32;
signal cache_v0, cache_v1: std_logic_vector(31 downto 0) := (others => '0');
signal lino_alu: std_logic_vector(15 downto 0);
signal cache_entry0, cache_entry1: std_logic_vector(31 downto 0);
alias cache_tag0: std_logic_vector(10 downto 0) is cache_entry0(15 downto 5); 
alias cache_data0: std_logic_vector(15 downto 0) is cache_entry0(31 downto 16);
alias cache_tag1: std_logic_vector(10 downto 0) is cache_entry1(15 downto 5); 
alias cache_data1: std_logic_vector(15 downto 0) is cache_entry1(31 downto 16);
signal cache_hit: std_logic_vector(1 downto 0);
signal cache_valid: std_logic_vector(1 downto 0);
signal cache_hit_alt_next_set, cache_valid_alt_for_set: std_logic;
signal cache_empty0, cache_empty1, cache_full0, cache_full1: std_logic;
signal cache_store_sel: std_logic;

-- other
signal T, T_saved: std_logic_vector(MSB downto 0);
signal lfsr: std_logic_vector(15 downto 0) := X"FFFF";
signal T_offset: std_logic_vector(15 downto 0);
signal S0, S1, S2: std_logic_vector(MSB downto 0);
signal tab_cnt: std_logic_vector(7 downto 0) := X"00";
signal at_tab: std_logic;
signal ready_alt_break: std_logic;
signal last3Chars: std_logic_vector(23 downto 0);
signal is_notRnd: std_logic;
signal s_equ_db_mod32: std_logic;
signal busack_clk: std_logic;

begin

-- GOTO cache, way 0
cache_empty0 <= '1' when (cache_v0 = X"00000000") else '0';		-- all 32 entries free
cache_full0 <= '1' when (cache_v0 = X"FFFFFFFF") else '0';		-- all 32 entries used
cache_entry0 <= cache_0(to_integer(unsigned(Lino_index)));		-- data/tag cache entry pointed to by Lino 
cache_valid(0) <= cache_v0(to_integer(unsigned(Lino_index)));
cache_hit(0) <= '1' when (cache_tag0 = Lino_tag) else '0';

-- GOTO cache, way 1
cache_empty1 <= '1' when (cache_v1 = X"00000000") else '0';		-- all 32 entries free
cache_full1 <= '1' when (cache_v1 = X"FFFFFFFF") else '0';		-- all 32 entries used
cache_entry1 <= cache_1(to_integer(unsigned(Lino_index)));		-- data/tag cache entry pointed to by Lino 
cache_valid(1) <= cache_v1(to_integer(unsigned(Lino_index)));
cache_hit(1) <= '1' when (cache_tag1 = Lino_tag) else '0';

-- GOTO cache outputs for fun
cache_empty <= cache_empty0 and cache_empty1;
cache_full <= cache_full0 and cache_full1;

-- Basic variable store
var_name <= X"7F" and std_logic_vector(unsigned(vars_index) + X"40");
var_address <= to_integer(unsigned(vars_index(4 downto 0)));
BasicVar <= vars(var_address);
BasicFor <= vars_for(var_address);
BasicNext <= vars_next(var_address);
for_set <= '0' when (BasicFor = X"0000") else for_v(var_address);
next_set <= '0' when (BasicNext = X"0000") else next_v(var_address);

-- Tristate system bus (64k address, bidirectional 8-bit data to Basic RAM "core")
DBUS <= MDR when ((nBUSACK = '1') and (mb_nWR = '0')) else "ZZZZZZZZ";
nRD <= mb_nRD when (nBUSACK = '1') else 'Z';
nWR <= mb_nWR when (nBUSACK = '1') else 'Z';
ABUS <= MAR when (nBUSACK = '1') else "ZZZZZZZZZZZZZZZZ";

busack_clk <= mb_nRD and mb_nWR and (not nBUSREQ);
on_busackclk: process(reset, busack_clk)
begin
	if ((reset = '1') or (nBUSREQ = '1')) then
		nBUSACK <= '1';
	else
		if (rising_edge(busack_clk)) then
			nBUSACK <= '0';
		end if;
	end if;
end process;

update_MAR: process(clk, mb_MAR)
begin
	if (rising_edge(clk)) then
		case mb_MAR is
	--			when MAR_same =>
	--				MAR <= MAR;
			when MAR_InlEnd =>
				MAR <= InlEnd;
			when MAR_BP =>
				MAR <= BP;
			when MAR_T =>
				MAR <= T(15 downto 0);
			when others =>
				null;
		end case;
	end if;
end process;

is_notRnd <= '0' when (last3Chars = X"524E44") else '1';	-- magic number is ASCII for RND
 
update_MDR: process(clk, mb_MDR)
begin
	if (rising_edge(clk)) then
		case mb_MDR is
	--			when MDR_same =>
	--				MDR <= MDR;
			when MDR_from_Bus =>
				MDR <= DBUS;
				-- HACKHACK: track last 3 read chars to compare if they were "RND" - if so, disable overflow check
				if ((unsigned(DBUS) > 96) and (unsigned(DBUS) < 123)) then
					last3Chars <= last3Chars(15 downto 0) & std_logic_vector(unsigned(DBUS) - 32);	-- definitely lowercase
				else
					last3Chars <= last3Chars(15 downto 0) & DBUS;												-- presumed uppercase
				end if;
				-- End hack
			when MDR_zero =>
				MDR <= (others => '0');
			when MDR_CHARIN =>
				MDR <= CHARIN;
			when MDR_ToUpper =>
				-- only touch lowercase a-z and convert to A-Z
				if (mdr_is_lowercase = '1') then
					MDR <= std_logic_vector(unsigned(MDR) - 32);
				end if;
			when MDR_from_SHi =>
				MDR <= S(15 downto 8);
			when MDR_from_SLo =>
				MDR <= S(7 downto 0);
			when MDR_from_microcode =>
				MDR <= '0' & mb_directByte;
			when others =>
				null;
		end case;
	end if;
end process;

-- IL program memory bus (2k address, 8-bit ready only input)
	IL_A <= IL_PC;
-- note that il_op is any data returned by this bus, at instruction fetch this is loaded to IL_OP
-- which is the CPU 8-bit instruction register

-- mapping IL opcode to microcode routine start
mb_instructionstart <= mb_mapper(to_integer(unsigned(il_op)));

-- control unit
cu_mb: entity work.microbasic_control_unit
     Generic map (
			CODE_DEPTH => CODE_ADDRESS_WIDTH,
			IF_WIDTH => CODE_IF_WIDTH
     )
     Port map ( 
			-- standard inputs
			reset => reset,
			clk => clk,
			-- design specific inputs
			seq_cond => mb_seq_cond,
			seq_then => mb_seq_then,
			seq_else => mb_seq_else,
			seq_fork => mb_instructionstart(8 downto 0),	-- IL opcode mapper input
			
			-- condition bits
			cond(seq_cond_true) => '1',
			cond(seq_cond_ILCODEBYTE_BIT7) => il_codebyte(7),
			cond(seq_cond_CHAROUT_READY) => outchar_ready,
			cond(seq_cond_IS_CPU32) => IS_CPU32,
			cond(seq_cond_DBG_READY) => ready_alt_break,
			cond(seq_cond_MDR_MATCHES_DB) => mdr_matches_db,
			cond(seq_cond_NREADY) => (nREADY or (not nBUSACK)),
			cond(seq_cond_INLEND_MAX) => inlend_max_alt_basline_found,
			cond(seq_cond_INLEND_MIN) => inlend_min_alt_impline_empty,
			cond(seq_cond_CHARIN_PRINTABLE) => charin_printable,
			cond(seq_cond_CHARIN_EQU_DB) => charin_equ_db,
			cond(seq_cond_CHARIN_READY) => charin_ready,
			cond(seq_cond_BP_IN_INPLINE) => bp_in_inpline,
			cond(seq_cond_SVP_IN_INPLINE) => svp_in_inpline,
			cond(seq_cond_MDR_IS_NUM) => mdr_is_num,
			cond(seq_cond_MDR_IS_ALPHA) => mdr_is_alpha,
			cond(seq_cond_STACK_IS_FULL) => stack_is_full,
			cond(seq_cond_STACK_IS_EMPTY) => stack_is_empty,
			cond(seq_cond_MDR_MATCHES_ILCODEBYTE) => mdr_matches_ilcodebyte_alt_varname,
			cond(seq_cond_R_IS_ZERO) => r_is_zero,
			cond(seq_cond_Y_ZERO) => y_zero_alt_cp_skip,
			cond(seq_cond_Y_SIGN) => y_sign_alt_intreq,
			cond(seq_cond_ALU_READY) => alu_ready,
			cond(seq_cond_ALU_OVERFLOW) => (overflowEnable and is_notRnd and alu_overflow),
			cond(seq_cond_ALU_SIGN) => alu_sign,
			cond(seq_cond_AT_TAB) => at_tab,
			cond(seq_cond_OFF_IS_ZERO) => off_is_zero,
			cond(seq_cond_IS_RUNMODE) => is_runmode,
			cond(seq_cond_S_EQU_DB_MOD32) => s_equ_db_mod32,	
			cond(seq_cond_CACHE_VALID) => cache_valid_alt_for_set,
			cond(seq_cond_CACHE_HIT) => cache_hit_alt_next_set,
			cond(seq_cond_false) => '0',
			-- outputs
			ui_nextinstr => ui_nextinstr,
			ui_address => ui_address
		);

-- priority encoder to get new external priority level
il_new <= 	"0111" when NMI = '1' else
				-- 5 additional priority layers possible here
				"0001" when INT = '1' else
				"0000";			-- no external signal means no interrupt

-- only react to interrupts while running Basic and of higher priority than current	
update_il: process(clk, reset, clk)
begin
	if ((reset = '1') or (is_runmode = '0')) then
		il_current <= (others => '0');
		il_previous <= (others => '0');
		intreq <= '0';
	else
		if (rising_edge(clk)) then
			if (intreq = '0' and (unsigned(il_new) > unsigned(il_current))) then
				intreq <= '1';
				il_previous <= il_current;
				il_current <= il_new;
			else
				if (INTACK = '1') then
					intreq <= '0';
				end if;
			end if;
			-- pick up previous level if returning from Basic subroutine
			if (mb_BasStack = BasStack_pop) then
				il_current <= BasStack(to_integer(unsigned(BasSP)))(35 downto 32);
			end if;
		end if;
	end if;
end process;

-- GOSUB 32000+(100*il_current) to call interrupt handling Basic subroutine
-- note that at this point il_current should have already captured the "new" level (see above)
lino_int <= INT_VECTORS(to_integer(unsigned(il_current)));

-- few condition codes come from two very different sources, but we can always (?) differentiate
y_sign_alt_intreq <= intreq when (executing_nx = '1') else Y(MSB);

-- simply ignore CTRL/C while the trace output is ongoing
ready_alt_break <= charin_is_break when (DBGINDEX = "000000") else DBG_READY;

-- inlend max and min only used in GL (Get Line, opcode 0x27)
basline_found <= '0' when ((LS = X"0000") or (LE = X"0000")) else '1';
inlend_max_alt_basline_found <= inlend_max when (IL_OP = OP_GL) else basline_found;

impline_empty <= '1' when (BE <= BP) else '0';
inlend_min_alt_impline_empty <= inlend_min when (IL_OP = OP_GL) else impline_empty;

-- Basic condition pass is only meaningful during CP (ComPare, opcode 0x1C) instruction
cp_skip <= (T(CP_OFF + 2) and s_gt_r) or (T(CP_OFF + 1) and s_equ_r) or (T(CP_OFF) and s_minus_r(MSB));
y_zero_alt_cp_skip <= cp_skip when (IL_OP = OP_CP) else y_zero;

-- GOTO cache and FOR/NEXT
cache_valid_alt_for_set <= (cache_valid(0) or cache_valid(1)) when (IL_OP = OP_GO) else for_set;
cache_hit_alt_next_set <= ((cache_hit(0) and cache_valid(0)) or (cache_hit(1) and cache_valid(1))) when (IL_OP = OP_GO) else next_set;

-- other conditional codes
mdr_matches_ilcodebyte_alt_varname <= mdr_matches_varname when (IL_OP = OP_FS) else mdr_matches_ilcodebyte;
mdr_matches_ilcodebyte <= 	'1' when (MDR_UpperCase(6 downto 0) = il_codeByte(6 downto 0)) else '0';
mdr_matches_varname <=		'1' when (MDR_UpperCase(6 downto 0) = var_name(6 downto 0)) else '0';
mdr_matches_db <=				'1' when (MDR_UpperCase(6 downto 0) = mb_directByte) else '0';
--mdr_equ_db <=			'1' when (MDR(6 downto 0) = mb_directByte) else '0';
mdr_is_num <=			'1' when ((unsigned(MDR) > 47) and (unsigned(MDR) < 58)) else '0';
mdr_is_lowercase <=	'1' when ((unsigned(MDR) > 96) and (unsigned(MDR) < 123)) else '0';
mdr_is_uppercase <=	'1' when ((unsigned(MDR) > 64) and (unsigned(MDR) < 91)) else '0';
mdr_is_alpha <= 		mdr_is_lowercase or mdr_is_uppercase;
charin_equ_db <=		'1' when (CHARIN(6 downto 0) = mb_directByte) else '0';
charin_printable <=	'0' when (CHARIN(7 downto 5) = "000") else (not CHARIN(7)); -- TODO: Add 0x7F 
inlend_max <=			'1' when (InlEnd = InLine_End) else '0';
inlend_min <=			'1' when (InlEnd = InLine_Start) else '0';
bp_in_inpline <=		'1' when ((unsigned(BP) >= unsigned(InLine_Start)) and (unsigned(BP) <= unsigned(InLine_End))) else '0';
svp_in_inpline <=		'1' when ((unsigned(SvPt) >= unsigned(InLine_Start)) and (unsigned(SvPt) <= unsigned(InLine_End))) else '0';
at_tab <= 				'1' when (tab_cnt(2 downto 0) = "000") else '0';
r_is_zero <= 			r_is_zero_full when (IL_OP = OP_DV) else r_is_zero_16;					
off_is_zero	<=			'1' when (IL_OFF5 = "00000") else '0';
y_zero <=				'1' when (Y(MSB downto 0) = ZERO) else '0';
is_runmode <=			'0' when (Lino = X"0000") else '1';
s_equ_db_mod32 <=		'1' when (S(4 downto 0) = mb_directByte(4 downto 0)) else '0';

-- for divide instruction check full R to prevent divide by 0, for other operations R is memory address or line number (16 bit)
r_is_zero_full <= 	'1' when (R = ZERO) else '0';
r_is_zero_16 <=		'1' when (R(15 downto 0) = X"0000") else '0';					

-- stack error conditions. Stack pointers point to first empty position. So if SP is 0 can't be pulled from, 
-- and if full (7 or 15) then can't be pushed onto. 
estack_is_full <= 	'1' when (ExpSP = "11111") else '0';
estack_is_empty <=	'1' when (ExpSP = "00000") else '0';
rstack_is_full	<=		'1' when (RetSP = X"F") else '0';
rstack_is_empty <=	'1' when (RetSP = X"0") else '0';
bstack_is_full	<=		'1' when (BasSP = X"F") else '0';
bstack_is_empty <=	'1' when (BasSP = X"0") else '0';

-- we need a "to_upper()" copy of MDR for case insensitive comparison
MDR_UpperCase <= std_logic_vector(unsigned(MDR) - X"20") when (mdr_is_lowercase = '1') else MDR;

-- select right stack condition based on IL_OP (currently executed opcode)
with IL_OP select stack_is_empty <= 
	rstack_is_empty when OP_RT,	-- RT (IL return)
	bstack_is_empty when OP_RS,	-- RS (Basic RETURN)
	estack_is_empty when others;
	
with IL_OP select stack_is_full <= 
	rstack_is_full when X"30" | X"31" | X"32" | X"33" | X"34" | X"35" | X"36" | X"37", -- JS
	bstack_is_full when OP_GS,		-- GS (Basic GOSUB)
	estack_is_full when others;
		
-- get the microcode instruction 
mb_uinstruction <= mb_microcode(to_integer(unsigned(ui_address)));
		
--------------------------------------------------------------------------------
-- Basic CPU has a program counter, instruction register, internal return stack
--------------------------------------------------------------------------------		
update_IL_PC: process(clk, mb_IL_PC)
 begin
	if (rising_edge(clk)) then
		case mb_IL_PC is
--			when IL_PC_same =>
--				IL_PC <= IL_PC;
			when IL_PC_XQhere =>
				IL_PC <= XQhere;
			when IL_PC_inc =>
				IL_PC <= std_logic_vector(unsigned(IL_PC) + 1);
			when IL_PC_T =>
				IL_PC <= T(10 downto 0);
			when IL_PC_pc_plus_off6 =>
				if (IL_OP = OP_SA) then
					-- pc_plus_off8 is the alternative effect to jump to default case
					IL_PC <= std_logic_vector(unsigned(IL_PC) + unsigned(il_codeByte));
				else
					-- a bit bizarre offset
					IL_PC <= std_logic_vector(unsigned(IL_PC) + unsigned(IL_OP) - 96);
				end if;
			when IL_PC_pc_plus_off5 =>
				if (IL_OP = OP_SA) then
					-- pc_plus_off2alpha is the alternative effect for case when MDR is alpha
					IL_PC <= std_logic_vector(unsigned(IL_PC) + (unsigned(MDR) - 65) + (unsigned(MDR) - 65) + 1);
				else
					-- can only jump forward
					IL_PC <= std_logic_vector(unsigned(IL_PC) + unsigned(IL_OFF5));
				end if;
			when IL_PC_direct11 =>
				-- top 3 bits from IL_OP, lower 8 from code pointed by IL
				IL_PC <= IL_OP(2 downto 0) & il_codeByte;
			when IL_PC_RetStack =>
				-- RetSP points to first free location
				-- we cannot modify RetSP here, so must be combined with "pop" operation on RetStack
				IL_PC <= RetStack(to_integer(unsigned(RetSP) - 1))(10 downto 0);
			when others =>
				null;
		end case;
 end if;
end process;

-- holds the start address of Basic input loop (which is 0), or if any program has run, the address of the
-- XQ (execute) instruction. Knowing this entry point is needed to restart program runs
 update_XQhere: process(clk, mb_XQhere)
 begin
	if (rising_edge(clk)) then
	    if (mb_XQhere = XQhere_T) then
		    XQhere <= T(10 downto 0);
	    end if;
 end if;
 end process;

-- instruction register
 update_IL_OP: process(clk, mb_IL_OP)
 begin
	if (rising_edge(clk)) then
	    if (mb_IL_OP = IL_OP_from_interpreter) then
		    IL_OP <= il_codeByte;
	    end if;
 end if;
 end process;
		
 update_RetStack: process(clk, mb_RetStack)
 begin
	if (rising_edge(clk)) then
		case mb_RetStack is
--			when RetStack_same =>
--				RetStack <= RetStack;
			when RetStack_clear =>
				RetSP <= (others => '0');
			when RetStack_pop =>
				RetSP <= std_logic_vector(unsigned(RetSP) - 1);
			when RetStack_push_IL_PC_PLUS_1 =>
				RetStack(to_integer(unsigned(RetSP))) <= "00000" & std_logic_vector(unsigned(IL_PC) + 1);
				RetSP <= std_logic_vector(unsigned(RetSP) + 1);
			when others =>
				null;
		end case;
 end if;
 end process;
		
 update_BasStack: process(clk, mb_BasStack)
 begin
	if (rising_edge(clk)) then
		case mb_BasStack is
--			when BasStack_same =>
--				BasStack <= BasStack;
			when BasStack_clear =>
				BasSP <= (others => '0');
			when BasStack_pop =>
				BasSP <= std_logic_vector(unsigned(BasSP) - 1);
			when BasStack_push_Lino_and_BP =>
				-- push also the interrupt level to restore it with last RETURN in interrupt service routine
				BasStack(to_integer(unsigned(BasSP))) <= il_previous & Lino & BP; 
				BasSP <= std_logic_vector(unsigned(BasSP) + 1);
			when others =>
				null;
		end case;
 end if;
 end process;
		
update_T: process(clk, mb_T)
begin
	if (rising_edge(clk)) then
		case mb_T is
--			when T_same =>
--				T <= T;
			when T_IL_PC =>
				T(MSB downto 11) <= (others => '0');
				T(10 downto 0) <= IL_PC;
			when T_XQhere =>
				T(MSB downto 11) <= (others => '0');
				T(10 downto 0) <= XQhere;
			when T_from_vars =>
				T <= BasicVar;
			when T_ExpStack =>
				T <= ExpSTHi & ExpSTLo;
			when T_from_YLo =>
				T <= Y(MSB downto 0);
			when T_from_YHi =>
				T <= Y(MSB_DOUBLE downto (MSB + 1));
			when T_zero =>
				T <= (others => '0');
			when T_codeByte =>
				T(MSB downto 8) <= (others => '0');	
				T(7 downto 0) <= il_codeByte;	
			when T_MDR =>	
				T(MSB downto 8) <= (others => '0');
				T(7 downto 0) <= MDR;
			when T_MDRx2 =>	
				-- assume it is already uppercased, otherwise a and A would be different variables!
				T(MSB downto 8) <= (others => '0');
				T(7 downto 0) <= MDR(6 downto 0) & '0';
			when T_inc =>
				T <= std_logic_vector(unsigned(T) + 1);
			when T_dec =>
				T <= std_logic_vector(unsigned(T) - 1);
			when T_BP =>
				T(MSB downto 16) <= (others => '0');
				T(15 downto 0) <= BP;
			when T_Prog_start =>
				T(MSB downto 16) <= (others => '0');
				T(15 downto 0) <= Prog_Start;
			when T_PrgEnd =>
				T(MSB downto 16) <= (others => '0');
				T(15 downto 0) <= PrgEnd;	
			when T_from_S =>
				T <= S;
			when T_from_R =>
				T <= R;
			when T_save =>
				T_saved <= T;
			when T_recall =>
				T <= T_saved;
			when T_BasStack_Hi =>
				T(MSB downto 16) <= (others => '0');
				T(15 downto 0) <= BasStack(to_integer(unsigned(BasSP) - 1))(31 downto 16);
			when T_BasStack_Lo =>
				T(MSB downto 16) <= (others => '0');
				T(15 downto 0) <= BasStack(to_integer(unsigned(BasSP) - 1))(15 downto 0);
			when T_Cache_Data =>
				T(MSB downto 16) <= (others => '0');
				if ((cache_valid(0) and cache_hit(0)) = '1') then
					-- HIT in way 0
					T(15 downto 0) <= cache_data0;
				else
					if ((cache_valid(1) and cache_hit(1)) = '1') then
						-- HIT in way 1
						T(15 downto 0) <= cache_data1;
					else
						-- MISS
						T(15 downto 0) <= (others => '0');
					end if;
				end if;
			when T_LS =>
				T(MSB downto 16) <= (others => '0');
				T(15 downto 0) <= LS;
			when T_binop =>
				-- S	operation
				-- 0	T NOR R
				-- 1	T NOR /R
				-- 2 	/T NOR R
				-- 3	T AND R
				-- 4	T OR S
				-- 5	T OR /S
				-- 6	/T OR S
				-- 7	T NAND R				
				T <= S2 xor ((S1 xor T) nor (S0 xor R));
			when T_fromTicks =>
				T(MSB downto 16) <= (others => '0');
				T(15 downto 0) <= cnt_perf1000;

				T_saved(MSB downto 16) <= (others => '0');
				T_saved(15 downto 0) <= cnt_perf;
			when T_from_var_For =>
				T(MSB downto 16) <= (others => '0');
				T(15 downto 0) <= BasicFor;
			when T_from_var_Next =>
				T(MSB downto 16) <= (others => '0');
				T(15 downto 0) <= BasicNext;
			when T_index2address =>
				T(MSB downto 16) <= (others => '0');
				T(15 downto 0) <= std_logic_vector(unsigned(PrgEnd) + unsigned(T_offset));
			when T_Core_End =>
				-- TODO: CoreEnd should not be a constant!
				T(MSB downto 16) <= (others => '0');
				T(15 downto 0) <= Core_End;		
			when T_from_microcode =>
				T <= ZERO(MSB downto 7) & mb_directByte;
			when T_from_lfsr =>
				T(MSB downto 16) <= (others => '0');
				T(15 downto 0) <= lfsr and X"7FFF";
			when others =>
				null;
		end case;
 end if;
end process;

-- index offsets for 2 (16-bit) or 4 (32-bit) byte elements	
T_offset <= (T(13 downto 0) & "01") when (IS_CPU32 = '1') else (T(14 downto 0) & '1');	

-- masks for T_binop
S0 <= (others => S(0));
S1 <= (others => S(1));
S2 <= (others => S(2));
	
 update_BP: process(clk, mb_BP)
 begin
	if (rising_edge(clk)) then
		case mb_BP is
--			when BP_same =>
--				BP <= BP;
			when BP_InLine_start =>
				BP <= InLine_Start;
			when BP_SvPt =>
				BP <= SvPt;
			when BP_inc =>
				BP <= std_logic_vector(unsigned(BP) + 1);
			when BP_save =>
				BP_saved <= BP;
			when BP_recall =>
				BP <= BP_saved;
			when BP_T =>
				BP <= T(15 downto 0);
			when BP_LS =>
				BP <= LS;
			when others =>
				null;
		end case;
 end if;
 end process;

 update_SvPt: process(clk, mb_SvPt)
 begin
	if (rising_edge(clk)) then
		case mb_SvPt is
--			when SvPt_same =>
--				SvPt <= SvPt;
			when SvPt_InLine_start =>
				SvPt <= InLine_Start;
			when SvPt_BP =>
				SvPt <= BP;
			when others =>
				null;
		end case;
 end if;
 end process;
	
-- input buffer pointer
 update_InlEnd: process(clk, mb_InlEnd)
 begin
	if (rising_edge(clk)) then
		case mb_InlEnd is
--			when InLend_same =>
--				InLend <= InLend;
			when InlEnd_InLine_start =>
				InLend <= InLine_Start;
			when InlEnd_inc =>
				InlEnd <= std_logic_vector(unsigned(InlEnd) + 1);
			when InLend_dec =>
				InlEnd <= std_logic_vector(unsigned(InlEnd) - 1);
			when others =>
				null;
		end case;
 end if;
 end process;
	
 -- WARNING: this can easily wrap around and destroy the stack!
 ExpSwapS <= std_logic_vector(unsigned(ExpSP) - 1); 
 ExpSwapR <= std_logic_vector(unsigned(ExpSP) - 1 - unsigned(IL_OP(2 downto 0))); 
 
 -- Stack top value
 ExpSTHi <= ExpStack(to_integer(unsigned(ExpSP) - 2));
 ExpSTLo <= ExpStack(to_integer(unsigned(ExpSP) - 1));

 -- ExpSP points to first free byte on the stack!
 update_ExpStack: process(clk, mb_ExpStack)
 begin
	if (rising_edge(clk)) then
		case mb_ExpStack is
--			when ExpStack_same =>
--				ExpStack <= ExpStack;
			when ExpStack_clear =>
				ExpStack(0) <= (others => '0');
				ExpSP <= (others => '0');
				INTACK <= '0';
			when ExpStack_push_TWord =>
				if ((executing_nx = '1') and (intreq = '1')) then
					-- HACKHACK to push interrupt service Basic line number onto stack, to be picked up by GO
					ExpStack(to_integer(unsigned(ExpSP) + 0)) <= LINO_INT(MSB downto (MSB_HALF + 1));
					ExpStack(to_integer(unsigned(ExpSP) + 1)) <= LINO_INT(MSB_HALF downto 0);
					INTACK <= '1';
				else
					-- T to next 2 free locations, MSB first
					ExpStack(to_integer(unsigned(ExpSP) + 0)) <= T(MSB downto (MSB_HALF + 1));
					ExpStack(to_integer(unsigned(ExpSP) + 1)) <= T(MSB_HALF downto 0);
					INTACK <= '0';
				end if;
				ExpSP <= std_logic_vector(unsigned(ExpSP) + 2);
			when ExpStack_push_TByte =>
				-- T.LSB to next free location
				ExpStack(to_integer(unsigned(ExpSP) + 0)) <= T(MSB_HALF downto 0);
				ExpSP <= std_logic_vector(unsigned(ExpSP) + 1);
				INTACK <= '0';
			when ExpStack_startSwap =>
				SwapS <= ExpStack(to_integer(unsigned(ExpSwapS)));
				SwapR <= ExpStack(to_integer(unsigned(ExpSwapR)));
				INTACK <= '0';
			when ExpStack_endSwap =>
				ExpStack(to_integer(unsigned(ExpSwapS))) <= SwapR;
				ExpStack(to_integer(unsigned(ExpSwapR))) <= SwapS;
				INTACK <= '0';
			when ExpStack_pop1 => 
				-- combine with assigment to some other 8-bit register
				ExpSP <= std_logic_vector(unsigned(ExpSP) - 1);
				INTACK <= '0';
			when ExpStack_pop2 => 
				-- combine with assigment to some other 16-bit register
				ExpSP <= std_logic_vector(unsigned(ExpSP) - 2);
				INTACK <= '0';
			when others =>
				INTACK <= '0';
		end case;
 end if;
 end process;
	
 update_Vars: process(clk, reset, mb_Vars)
 begin
--	if (reset = '1') then
--		for_v <= (others => '0');
--		next_v <= (others => '0');
--	else
		if (rising_edge(clk)) then

			-- clear for/next state at start of run (when Lino goes from 0 to some valid Basic line number)
			lino_var <= Lino;
			if ((is_runmode = '1') and (lino_var = X"0000")) then
				for_v <= (others => '0');
				next_v <= (others => '0');
			end if;
		
			case mb_Vars is
		--			when Vars_same =>
		--				Vars <= Vars;
				when Vars_indexFromExpStack =>
					-- top byte on expressions stack (ExpSTLo) contains twice the upper - case ASCII code of the variable name
					vars_index <= std_logic_vector(unsigned('0' & ExpSTLo(7 downto 1)) - X"40");
				when Vars_T =>
					Vars(var_address) <= T;
				when Vars_for_fromLino =>
					Vars_For(var_address) <= Lino;
					for_v(var_address) <= '1';
				when Vars_next_fromBP =>
					Vars_Next(var_address) <= BP;
					next_v(var_address) <= '1';
				when Vars_for_clear =>
					Vars_For(var_address) <= X"0000";
					for_v(var_address) <= '0';
				when Vars_next_clear =>
					Vars_Next(var_address) <= X"0000";
					next_v(var_address) <= '0';
				when others =>
					null;
			end case;
		end if;
--	end if;
 end process;
	
-------------------------------------------------------------------------------	
-- output port (1 ASCII char at a time, usually goes to UART)
-- TODO: implement outgoing FIFO
-------------------------------------------------------------------------------
 is_pq <= '1' when (IL_OP = OP_PQ) else '0';
 hex_ascii <= hex2ascii(to_integer(unsigned(Y(MSB_DOUBLE downto (MSB_DOUBLE - 3)))));
 
 update_CHAROUT: process(clk, mb_CHAROUT)
 begin
	if (rising_edge(clk)) then
		outchar_send <= CHAROUT_SEND;				-- delay send signal 1 clock cycle
		case mb_CHAROUT is
			when CHAROUT_same =>
				CHAROUT_SEND <= '0';					-- pulse low
				--CHAROUT <= CHAROUT;
			when CHAROUT_from_interpreter =>
				lz <= '1';
				CHAROUT_SEND <= '1';					-- pulse high when data loaded
				CHAROUT <= il_codeByte;
			when CHAROUT_from_microcode =>
				lz <= '1';
				CHAROUT_SEND <= '1';					-- pulse high when data loaded
				CHAROUT <= '0' & mb_directByte;	-- because we store only 7-bit ASCII in microcode
			when CHAROUT_from_charin =>
				lz <= '1';
				CHAROUT_SEND <= '1';					-- pulse high when data loaded
				CHAROUT <= CHARIN;
			when CHAROUT_from_MDR =>
				lz <= '1';
				if (caret_escape = '1') then
					-- escaping is on, always output a char and turn escaping off
					CHAROUT_SEND <= '1';
					caret_escape <= '0';				
					if ((MDR = CARET) or (MDR = CR)) then
						-- ^^ means we want to display the ^ and kill the escape mode
						CHAROUT <= MDR;
					else
						if ((mdr_is_uppercase = '1') or (MDR = SQBR_OPEN)) then
							-- ^ is followed by A..Z, this is now a control character!
							CHAROUT <= std_logic_vector(unsigned(MDR) - 64);
						else 
							-- escape has no effect on any other characters (except [ for ESC)
							CHAROUT <= MDR;
						end if;
					end if;
				else
					-- check if is off, check if it needs to be turned on
					CHAROUT <= MDR;
					if (MDR = CARET) then
						-- detected 1st ^ in sequence, turn on escaping, no send pulse
						caret_escape <= is_pq;			-- escaping only works in PQ instruction
						CHAROUT_SEND <= not(is_pq);	-- only swallow if in PQ
					else
						-- any other char in
						caret_escape <= '0';
						CHAROUT_SEND <= '1';			
					end if;
				end if;
			when CHAROUT_from_YtoAlpha =>				-- from top nibble of Y register, including zero
				lz <= '1';
				CHAROUT_SEND <= '1';						-- pulse high when data loaded
				CHAROUT <= hex_ascii;
			when CHAROUT_from_YtoAlphaZ =>			-- from top nibble of Y register, supress leading zero
				if (Y(MSB_DOUBLE downto (MSB_DOUBLE - 3)) = X"0") then
					if (lz = '0') then
						-- this is 0 but previous was not zero, so need to output
						CHAROUT_SEND <= '1';			  
						CHAROUT <= hex_ascii;
					end if;
				else
					-- not zero, so clear the leading zero flag to output subsequent zeroes
					CHAROUT_SEND <= '1';	
					CHAROUT <= hex_ascii;
					lz <= '0';
				end if;
			when others =>
				null;
		end case;
 end if;
 end process;
  
-- watch the output characters to update the TAB counter
on_charout_send: process(CHAROUT_SEND, reset)
begin
	if (reset = '1') then
		tab_cnt <= (others => '0');
	else
		if (rising_edge(CHAROUT_SEND)) then
			case CHAROUT is
				when CR =>	-- CR resets to left margin
					tab_cnt <= (others => '0');
				when BS => -- BS goes one space left
					tab_cnt <= std_logic_vector(unsigned(tab_cnt) - 1);
				when NUL => -- NULL does nothing
					null;
				when others => -- all other (non-control) characters advance
					if (CHAROUT(7 downto 5) /= "000") then 
						tab_cnt <= std_logic_vector(unsigned(tab_cnt) + 1);
					end if;
			end case;
		end if;
	end if;
end process; 

-- see http://www.ittybittycomputers.com/IttyBitty/TinyBasic/TinyBasic.c line 776
outchar <= CHAROUT and X"7F";
 
------------------------------------------------------------------------------------ 
-- input character
-- external device presents the char code at inchar input port and raises inchar_ready signal
-- inchar_ready is a condition for microcode to know there is a new char, but must raise 
-- mb_gotChar to reset the charin_ready flag
-- TODO: implement incoming FIFO
------------------------------------------------------------------------------------
on_inchar_ready: process(reset, inchar_ready, mb_gotChar)
begin
	if ((reset or mb_gotChar) = '1') then
		--CHARIN <= (others => '0');
		charin_ready <= '0';
		charin_is_break <= '0';
	else
		if (rising_edge(inchar_ready)) then
			CHARIN <= inchar;
			charin_ready <= '1';
			if (inchar = STX) then
				charin_is_break <= '1';
			else
				charin_is_break <= '0';
			end if;
		end if;
	end if;
end process;
	
--------------------------------------------------------------	
-- ALU (including R, S, Y and various bit-state registers)
--------------------------------------------------------------
 update_alu: process(clk, mb_alu)
 begin
	if (rising_edge(clk)) then
		-- clear cache valid bits at start of run (when Lino goes from 0 to some valid Basic line number)
		lino_alu <= Lino;
		if ((is_runmode = '1') and (lino_alu = X"0000")) then
			cache_v0 <= (others => '0');
			cache_v1 <= (others => '0');
			-- pseudo-random number seed
			if (PrgEnd = X"0000") then
				lfsr <= X"FFFF"; 
			else
				lfsr <= PrgEnd;	-- PrgEnd value changes at each Basic program edit 
			end if;
		else
			-- generate another pseudo-random 16-bit value
			lfsr(15) <= lfsr(0);
			lfsr(14) <= lfsr(15);
			lfsr(13) <= lfsr(14) xor lfsr(0);
			lfsr(12) <= lfsr(13) xor lfsr(0);
			lfsr(11) <= lfsr(12);
			lfsr(10) <= lfsr(11) xor lfsr(0);
			lfsr(9 downto 0) <= lfsr(10 downto 1);
		end if;
		case mb_alu is
--			when alu_nop =>
--				alu <= alu;
			when alu_reset0 =>
				R <= (others => '0');
				Y_saved <= (others => '0');
				S <= (others => '0');
				Y <= (others => '0');
				alu_ready <= '0';
				alu_overflow <= '0';
			when alu_reset1 =>
				R(MSB downto 16) <= (others => '0');
				R(15 downto 0) <= (others => '1');
				Y_saved <= (others => '0');
				S <= (others => '0');
				--Y <= (others => '0');
				alu_ready <= '0';
				alu_overflow <= '0';
			when alu_R_fromStack =>
				R <= ExpSTHi & ExpSTLo; 
			when alu_S_fromStack =>
				S <= ExpSTHi & ExpSTLo; 
			when alu_S_plus_R =>
				Y <= ZERO & s_plus_r;
				alu_ready <= '1';
				alu_overflow <= plus_overflow;
			when alu_S_minus_R =>
				Y <= ZERO & s_minus_r;
				alu_ready <= '1';
				alu_overflow <= minus_overflow;
			when alu_neg_R =>
				Y <= ZERO & neg_r;
				alu_ready <= '1';
				alu_overflow <= neg_overflow;
			when alu_S_mul_R =>
				Y <= s_mul_r;
				alu_ready <= '1';
				alu_overflow <= mul_overflow;
			when alu_Yx16 =>
				-- microcode should execute this EXACTLY 7 times to pick up 8 BCD digits!
				Y <= Y((MSB_DOUBLE - 4) downto 0) & X"0";	-- shift up by a nibble (== BCD digit)
			when alu_bcd_start =>
				-- first step
				if (R(MSB) = '1') then
					alu_sign <= '1';
					R <= neg_R;				-- BUGBUG -32768??
				else
					alu_sign <= '0';
				end if;
				S <= (others => '0');	-- prepare counter for bit 0 of R
				Y <= (others => '0');	-- clear BCD accumulator
				alu_ready <= '0';
				alu_overflow <= '0';		-- by implementation can't overflow
			when alu_bcd_next =>
				Y((MSB - 1) downto (BCDDIGITS * 4)) <= (others => '0');	-- 16-bit binary needs 6 BCD digits, so zero out high byte
				Y((BCDDIGITS * 4 - 1) downto 0) <= bcd_sum;	
				if ((S(4 downto 0) = BITCNT) or (R = ZERO)) then
					alu_ready <= '1';
				else
					alu_ready <= '0';
					S <= std_logic_vector(unsigned(S) + 1);
					R <= '0' & R(MSB downto 1);	-- shift down
				end if;
			-- Using restore division without the restoration addition cycle (with sign correction before/after)
			-- See "Digital Computer Arithmetic" by Joseph J.F. Cavanagh, page 254, ISBN 0-07-010282-1
			when alu_div_start =>	-- S / R 
				if (S(MSB) = '0') then
					-- S > 0
					-- NOTE: before this step, R is already checked for 0 (divide by 0 condition)
					if (R(MSB) = '0') then
						-- R >= 0
						R <= neg_r;	-- we need the -R for subtraction
						alu_sign <= '0';	-- +/+
					else
						-- R < 0, already good for substraction
						alu_sign <= '1';	-- -/+
					end if;
					Y <= ZERO & S;
				else
					-- S < 0
					if (R(MSB) = '0') then
						-- R >= 0
						R <= neg_r;	-- we need the -R for subtraction
						alu_sign <= '1';	-- +/-
					else
						-- R < 0
						alu_sign <= '0';	-- -/-
					end if;
					Y <= ZERO & neg_s;
				end if;	
				alu_s15 <= S(MSB);			-- will be used to correct the sign of remainder
				alu_overflow <= '0';		-- By definition can't overflow
				alu_ready <= '0';
				S(MSB downto 8) <= (others => '0');
				S(7 downto 0) <= STEPCNT;	-- use S as the 16 steps counter
			when alu_div_shift =>
				if (S = ZERO) then
					alu_ready <= '1';
				else
					Y <= Y((MSB_DOUBLE - 1) downto 0) & '0'; -- shift remainder and quotient up
					alu_ready <= '0';
				end if;
			when alu_div_subset =>
				if (S = ZERO) then
					alu_ready <= '1';
				else 
					S <= std_logic_vector(unsigned(S) - 1);
					alu_ready <= '0';	-- continue
					if (subc(MSB + 1) = '0') then
						Y <= Y(MSB_DOUBLE downto 1) & '0';
					else
						Y <= subc(MSB downto 0) & Y(MSB downto 1) & '1';
					end if;
				end if;
			when alu_div_end =>
				if (alu_sign = '1') then
					-- correct quotient sign
					YLo <= neg_ylo;
				end if;
				if (alu_s15 = '1') then
					-- correct remainder sign (otherwise remainder would be always positive or zero)
					YHi <= neg_yhi;
				end if;
			when alu_Yx10_plus_MDR =>
				-- used for string to numeric conversion
				Y <=  std_logic_vector((10 * unsigned(Y(MSB downto 0))) + (unsigned(MDR) - 48));
				if (Y(MSB_DOUBLE downto (MSB + 1)) = ZERO) then	-- BUGBUG, this is checked one cycle late
					alu_overflow <= '0';
				else
					alu_overflow <= '1';
				end if;
			when alu_Rx256_plus_MDR =>
				-- used for 2 bytes searches in memory
				R <= R((MSB - 8) downto 0) & MDR;
			when alu_S_fromT =>
				S <= T;
			when alu_R_fromT =>
				R <= T;
			when alu_S_fromLino =>
				S(MSB downto 16) <= (others => '1');
				S(15 downto 0) <= Lino;
			when alu_copy_init_del =>
				S(MSB downto 16) <= (others => '0');
				R(MSB downto 16) <= (others => '0');
				Y(MSB_DOUBLE downto 16) <= (others => '0');
				S(15 downto 0) <= std_logic_vector(unsigned(LE) + 1);
				R(15 downto 0) <= LS;
				Y(15 downto 0) <= std_logic_vector(unsigned(PrgEnd) - unsigned(LE));
			when alu_copy_next =>
				if (unsigned(S) > unsigned(R)) then 
					S <= std_logic_vector(unsigned(S) + 1);
					R <= std_logic_vector(unsigned(R) + 1);
				else 
					S <= std_logic_vector(unsigned(S) - 1);
					R <= std_logic_vector(unsigned(R) - 1);
				end if;
				Y <= std_logic_vector(unsigned(Y) - 1);
			when alu_copy_init_ins =>
				S(MSB downto 16) <= (others => '0');
				R(MSB downto 16) <= (others => '0');
				Y(MSB_DOUBLE downto 16) <= (others => '0');
				S(15 downto 0) <= PrgEnd;
				R(15 downto 0) <= std_logic_vector(unsigned(PrgEnd) + unsigned(BE) - unsigned(BP) + 3);
				Y(15 downto 0) <= std_logic_vector(unsigned(PrgEnd) - unsigned(LS) + 1);
			when alu_ls_load =>
				-- initialize for LS (list) opcode
				-- S = start line, R = end line, store both to Y and check values
				if (S(15 downto 0) = X"FFFF") then
					-- 1 param given on command line, so start and end should be that
					Y <= R & R;				
					ls_params_ok <= '1';					
				else 
					if (R(15 downto 0) = X"FFFF") then
						-- no parameters? assume full range
						Y <= S & R;
						ls_params_ok <= '1';
					else
						-- two or no params on command line, check that start <= end
						if (unsigned(R(15 downto 0)) <= unsigned(S(15 downto 0))) then
							Y <= R & S;
							ls_params_ok <= '1';
						else
							ls_params_ok <= '0';
						end if;
					end if;
				end if;
			when alu_ls_check =>
				-- HACKHACK for 32-bits
				R(MSB downto 16) <= (others => '0');
				-- check if current line with number R is in range previously saved in Y
				if (unsigned(R(15 downto 0)) > unsigned(ListTo)) then
					ls_passed_end <= '1';
					ls_in_range <= '0';
				else
					ls_passed_end <= '0';
					if (unsigned(R(15 downto 0)) >= unsigned(ListFrom)) then
						ls_in_range <= '1';
					else
						ls_in_range <= '0';
					end if;
				end if;
			when alu_Y_save =>
				Y_saved <= Y;
			when alu_Y_recall => 
				Y <= Y_saved;
			when alu_cache_store =>
				-- always write (or overwrite) - see cache_store_sel below for "strategy"
				if (cache_store_sel = '0') then
					cache_0(to_integer(unsigned(Lino_index))) <= BP & Lino;
					cache_v0(to_integer(unsigned(Lino_index))) <= '1';
				else
					cache_1(to_integer(unsigned(Lino_index))) <= BP & Lino;
					cache_v1(to_integer(unsigned(Lino_index))) <= '1';
				end if;
			when alu_for_check =>
				if (t_minus_s = ZERO) then
					alu_ready <= '1';
				else
					alu_ready <= R(MSB) xor (t_minus_s(MSB));
				end if;
			when alu_for_step =>
				Y <= ZERO & t_plus_r;
			when alu_S_swap32 =>
				-- swaps 2 16-bit words if CPU is 32-bit, or NOP for 16-bit 
				S(MSB downto (MSB - 15)) <= S(15 downto 0);
				S(15 downto 0) <= S(MSB downto (MSB - 15));
			when others =>
				null;
		end case;
 end if;
 end process;

with cache_valid select cache_store_sel <= 
	'1' when "01",			-- store to 1 which is free
	'0' when "10",			-- store to 0 which is free
	lfsr(0) when others;	-- select random one to overwrite
	
-- 17 bit subtract for division step
subc <= std_logic_vector(unsigned('0' & Y(MSB_DOUBLE downto (MSB + 1))) + unsigned('0' & R));

-- 6 digit BIN to BCD converter (unsigned)
converter: entity work.bin2bcd 
     Generic map (
			DIGITS => BCDDIGITS)
		Port map (
			power => S(4 downto 0),
			sel => R(0),
			sum_in => Y((BCDDIGITS * 4 - 1) downto 0),
			sum_out => bcd_sum
		);
 
-- combinatorial operations
s_plus_r <= std_logic_vector(signed(S) + signed(R));
plus_overflow <= ((not R(MSB)) and (not S(MSB))) when (s_plus_r(MSB) = '1') else (R(MSB) and S(MSB));
t_plus_r <= std_logic_vector(signed(T) + signed(R));
t_minus_s <= std_logic_vector(signed(T) - signed(S));

s_minus_r <= std_logic_vector(signed(S) - signed(R));
minus_overflow <= '0';
s_equ_r <= '1' when (s_minus_r = ZERO) else '0';
s_gt_r <= not(s_minus_r(MSB)) and not(s_equ_r);

neg_r <= std_logic_vector(0 - signed(R));
neg_overflow <= R(MSB) when (R((MSB - 1) downto 0) = ZERO((MSB - 1) downto 0)) else '0';	-- can't negate -32768

neg_s <= std_logic_vector(0 - signed(S));
neg_ylo <= std_logic_vector(0 - signed(YLo));
neg_yhi <= std_logic_vector(unsigned(YHi xor MINUS_ONE) + 1);

-- will use intrinsic multiplier on FPGA (which is also combinatorial, therefore this is synthesizable)
s_mul_r <= std_logic_vector(signed(R) * signed(S));
mul_pos16 <= '1' when (s_mul_r(MSB_DOUBLE downto MSB) = (ZERO & '0')) else '0';
mul_neg16 <= '1' when (s_mul_r(MSB_DOUBLE downto MSB) = (MINUS_ONE & '1')) else '0';
mul_overflow <= not(mul_pos16 or mul_neg16);

-- Basic line number
 update_Lino: process(clk, mb_Lino)
 begin
	if (rising_edge(clk)) then
	    if (mb_Lino = Lino_T) then
		    Lino <= T(15 downto 0);
	    end if;
 end if;
 end process;

-- End of command in input line
 update_BE: process(clk, mb_BE)
 begin
	if (rising_edge(clk)) then
	    if (mb_BE = BE_T) then
		    BE <= T(15 downto 0);
	    end if;
 end if;
 end process;

-- Start of line in Basic code
 update_LS: process(clk, mb_LS)
 begin
	if (rising_edge(clk)) then
	    if (mb_LS = LS_T) then
		    LS <= T(15 downto 0);
	    end if;
 end if;
 end process;

-- End of line in Basic code
 update_LE: process(clk, mb_LE)
 begin
	if (rising_edge(clk)) then
	    if (mb_LE = LE_T) then
		    LE <= T(15 downto 0);
	    end if;
 end if;
 end process;

-- End of program (points to 2nd of two NULL bytes that are at end of Basic code)
 update_PrgEnd: process(clk, mb_PrgEnd)
 begin
	if (rising_edge(clk)) then
	    if (mb_PrgEnd = PrgEnd_T) then
		    PrgEnd <= T(15 downto 0);
	    end if;
 end if;
 end process;

-------------------------------------------------------------------
-- Built-in debug and tracer components
-------------------------------------------------------------------
debug_t <= T(15 downto 0);		-- output T to show memory pointer
debug_uipc <= ui_address;		-- output microinstruction program counter to show microinstruction symbols

-- paralled debug port
	with debug_sel select debug_bus(23 downto 0) <= 
		(X"15" & LS) when "00",
		(X"1E" & LE) when "01",
		(X"B5" & BP) when "10",
		(X"5E" & PrgEnd) when others;

	debug_bus(31 downto 24) <= (traceEnable & is_runmode & "010000"); -- indicate "name.value" on LEDs

-- 
lino2bcd: entity work.bin2bcd_lut Port map ( 
		bin => Lino,
      bcd => Lino_bcd
		);

-- serial debug port
tracer: entity work.serialtracer2 Port map (
		reset => reset,
		clk => baudrate,
		enable => traceEnable,	-- TODO: override for some DBGINDEX values
		start => dbg_start,
		index => DBGINDEX,
		slevel => RetSp,
		--X"80"
		data(3) => '0',
		data(2 downto 0) => IL_PC(10 downto 8),
		--X"81"
		data(7 downto 4) => IL_PC(7 downto 4),
		--X"82"
		data(11 downto 8) => IL_PC(3 downto 0),
		--X"83"
		data(15 downto 12) => il_codeByte(7 downto 4),
		--X"84"
		data(19 downto 16) => il_codeByte(3 downto 0),
		--X"85"
		data(23 downto 20) => MDR(7 downto 4),
		--X"86"
		data(27 downto 24) => MDR(3 downto 0),
		--X"87"
		data(31 downto 28) => '0' & IL_OP(2 downto 0), -- interested in lower 3 bits only
		--X"88"..X"89"
		data(47 downto 32) => Lino_bcd(15 downto 0),
		data(63 downto 48) => T(15 downto 0),
		txd => debug_txd,
		ready => DBG_READY
		);

 update_DBGINDEX: process(clk, mb_DBGINDEX)
 begin
	if (rising_edge(clk)) then
		case mb_DBGINDEX is
--			when DBGINDEX_same =>
--				DBGINDEX <= DBGINDEX;
			when DBGINDEX_from_microcode =>
				DBGINDEX <= mb_directByte(5 downto 0);
				dbg_start <= '1';
			when DBGINDEX_zero =>
				DBGINDEX <= (others => '0');
				dbg_start <= '0';
			when DBGINDEX_crlf =>
				DBGINDEX <= (others => '1'); -- points to last index in the table
				dbg_start <= '1';
			when others =>
				null;
		end case;
 end if;
 end process;
		
-- perf counter while the program is running (to be displayed at the end of execution for performance evaluation)
pulse_fetch <= '1' when (mb_IL_OP = IL_OP_from_interpreter) else '0';
executing_nx <= '1' when (IL_OP = OP_NX) else '0';
executing_nc <= '1' when (IL_OP = OP_NC) else '0';

with debug_sel select clk_perf <= 
		clk_tick when "00",						-- count seconds.milliseconds of Basic program run time 
		outchar_send when "01",					-- count how many characters were output
		pulse_fetch when "10",					-- count IL instructions executed
		(executing_nx or executing_nc) when others;	-- count Basic statements executed

on_clk_perf: process(clk_perf, reset)
begin
	if (reset = '1') then
		cnt_perf <= (others => '0');
		cnt_perf1000 <= (others => '0');
		is_runmode_perf <= '0';		-- previous run mode
	else
		if (rising_edge(clk_perf)) then
			is_runmode_perf <= is_runmode;
			if (is_runmode = '1') then
				if (is_runmode_perf = '0') then
					-- going from stopped to running, reset counters
					cnt_perf <= (others => '0');
					cnt_perf1000 <= (others => '0');
				else
					-- when running, load increment counters
					if (cnt_perf = X"03E7") then		-- wrap around at 1000
						cnt_perf <= (others => '0');
						cnt_perf1000 <= std_logic_vector(unsigned(cnt_perf1000) + 1);
					else
						cnt_perf <= std_logic_vector(unsigned(cnt_perf) + 1);
					end if;
				end if;
			end if;
		end if;
	end if;
end process;

end Behavioral;

